server:
  port : 1233
spring:  h2:    console:      enabled: true
  #jersey:
    #application-path : api
 # datasource:
   # url: jdbc:/mysql://localhost:3306/testdb
    #username: root
    #password: pas@word1
  #jpa:
    #show-sql: true