server:
  port: 3344
spring:
  data:
    mongodb:
      database: todo-tab
      host: 127.0.0.1
      port: 27017
  application:
    name: todo-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka